sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- pypy
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
before_script:
- find ./bandwidth -name \*.py -exec pep8 --ignore=E402 --max-line-length 120 {} +
- find ./tests -name \*.py -exec pep8 --ignore=E402 --max-line-length 120 {} +
script: green tests -r -vvv
deploy:
  provider: pypi
  user: developerhelp-bandwidth
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Bandwidth/python-bandwidth
    branch: master
  password:
    secure: ZWDpRyoYVZJ9IyYBdUV36BKJ6kuMMYuIJ/OCzr5BxTcc/IQwLkksnC3lGauVewaGYVQXhAVIq55iO7dJoeX0IKKYws2Hh2rCmVBgXR2wXHMEtCqCwc7gHsOVD4SZkAcC7+3H68v1x7Xb9qwiq1FX6IuPJdBJNi8LWGf0b2YrlJ4Gz3RzniAbg4UEgLUDviHgjm6qye89MGPhBewhUYek311xgK1KMOhTFPgzmXW74XJSqI5oVCpSDDBiwGVIXKBPR1Yvjnul2b6JqpTAo0MxbAGDy5SItkf620lw2v2u6oY3tbzRTnv2av5RcpBstF1ca0O7Rb9FhkDfPOz5xUOzNtzw5HT129Ifa9P4Q+mzeLjn7e+I7H5Puq0Kkju7K3DSzTYuc9iNrvB5ZJexkY2S31IpvLdfu4xVjiq3CU56mDIFqrOd9MssFv06W8cQlmZqaPG1OyUPLBss0wOb2kzmaYQIdtBKsxXZlrr5gjEdcCdZ4Hsyrvn312kiSztL3j0d6/WrFQJIyZMvdxsVeQYadYTbjPlb+hd57uCN+5lGDQPG5mhW2QIwmrOM96HYW/KjcF75jSaTZMnVLW1yV+52fZlsPFHsP+0EE/6d5fq5U3O8j3F8BBGT3J+fxKLQGax5xgC6N2gt/eOrY/EH2vhIc3lAD4N1swUuJp35DTydi4Q=
